[Feature:Autograding] Add Salsa image
Submitty/DockerImages pull request #49
Opened 2024-09-11 16:47 UTC by ION606

### Please check if the PR fulfills these requirements:

* [x] Tests for the changes have been added/updated (if possible)
* [x] Documentation has been updated/added if relevant

### What is the current behavior?

none

### What is the new behavior?
we can now run salsa files

### Other information?

this is not a breaking change and I tested it using some simple files (I included an example below):

```salsa
module demo;

/*
   Actors with this behavior simply create a migrate actor with the specified UAN and first UAL    
   and then migrate to the second UAL.
*/
behavior Migrate {

   void print() {

      standardOutput<-println( "Migrate actor just migrated here." );
   }

   void act( String[] args ) {

         if (args.length != 3) {
                 standardOutput<-println( "Usage: java migration.Migrate  <UAN> <srcUAL> <destUAL> " );

                 return;
        }

        UAN uan = new UAN(args[0]);
        UAL ual = new UAL(args[1]);
        
        Migrate  migrateActor = new Migrate() at (uan, ual);
      
        migrateActor<-print() @ 
        migrateActor<-migrate( args[2] ) @ 
        migrateActor<-print(); 
         
   }     
    
}   
```

2024-09-11 16:48 UTC, ION606 commented
I should note that my compilation command is `java -cp $SALSA_COMPILER_JAR:. salsac.SalsaCompiler *.salsa; javac -classpath $SALSA_COMPILER_JAR:. *.java` instead of `java -cp $SALSAPATH/salsa$SALSAsalsac.SalsaCompiler \!*.salsa; javac -classpath $SALSAPATH/salsa$SALSAVER.jar:. \!*.java` because the latter doesn't work.

2024-09-25 01:03 UTC, cjreed121 requested changes

2024-09-25 01:03 UTC, cjreed121 commented on dockerfiles/salsa/1.1.6/Dockerfile
> +RUN curl -SL -o /usr/local/lib/salsa/salsa1.1.6.jar http://wcl.cs.rpi.edu/salsa/releases/salsa1.1.6.jar
Since this uses http, can you add a hash check on this. sha256 would be fine to use.

2024-09-25 01:03 UTC, cjreed121 commented on dockerfiles/salsa/1.1.6/Dockerfile
> +    && apt-get install -y openjdk-17-jdk curl --no-install-recommends \
`curl` can be removed after salsa jar is fetched

2024-10-11 16:03 UTC, merged